name: Build, push, and deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push request on the main branch for changes in the specified paths.
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'infra/'
      - 'README.md'

env:
  app: admin-server
  app_name: 'coral-app'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  deploy:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - name: Checkout
      uses: actions/checkout@main

    # Install doctl.
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Set container tag
      run: echo "tag=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
    
    # Build a Docker image of your application in your registry and tag the image with the $GITHUB_SHA.
    - name: Build container image
      run: docker build -t ${{ secrets.REGISTRY_NAME }}/${{env.app}}:${{ env.tag }} .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: docker push ${{ secrets.REGISTRY_NAME }}/${{env.app}}:${{ env.tag }}

    - name: Change App Docker tag
      uses: digitalocean/app_action@main
      with:
        app_name: ${{env.app_name}}
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        images:
          '[{
              "name": "${{env.app}}",
              "registory": "${{ secrets.REGISTRY_NAME }}",
              "registry_type": "DOCR",
              "repository": "${{env.app}}",
              "tag":"${{ env.tag }}"
          }]'